// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euckbyyrcrnpgdjgqfkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1Y2tieXlyY3JucGdkamdxZmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNjU1NTEsImV4cCI6MjA3MTg0MTU1MX0.s7KW1QJbX-J7cean357P4xvN6jGeEbWsV0zDq-GKgVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});