// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhmppcrjfkrmmeohxvrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5obXBwY3JqZmtybW1lb2h4dnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMzQ1OTAsImV4cCI6MjA3MTkxMDU5MH0.fei8IrE0POOwMtqhMugLKr5HnCBUPrOfVPEyZ25VZ7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});